1. 打印下面的值

```js
  const promise1 = new Promise((resolve, reject) => {
    reject()
  })

  const promise2 = promise1.then(null, function () {
   return 123
  })

  promise2.then(
    () => {
      console.log('promise2 已经完成')
    }, 
    () => {
      console.log('promise2 已经失败')
    })

  // promise2 已经完成
  // 原因在于每一次then方法都会返回一个新的Promise，状态是处于pending状态，此次promise将会转为fulfullied或rejected都是由新的promise内部代码决定的，由于promise1执行了reject，对应的promise2会执行function函数，返回123，变为fulfullied状态，then状态时将会执行resolve函数，即打印‘promise2 已经完成’
```

2. 打印下面的值

```js
  const promise1 = new Promise((resolve, reject) => {
    reject()
  })

  const promise2 = promise1.then(function () {
   return 123
  }, null)

  promise2.then(() => {
    console.log('promise2 已经完成')
  }, () => {
    console.log('promise2 已经失败')
  })

  // promise2 已经失败
```

3. 打印下面的值

```js
  const promise1 = new Promise((resolve, reject) => {
    reject()
  })

  const promise2 = promise1.then(function () {
   return {
     get then() {
      throw new Error('11111')
     }
   }
  }, null)

  promise2.then(() => {
    console.log('promise2 已经完成')
  }, () => {
    console.log('promise2 已经失败')
  })

  // promise2 已经失败
```

4. promise的封装技巧

5. promise.all如何防止某一个promise失败从而使整个promise失败？

```js
const promise1 = new Promise(resolve => setTimeout(resolve, 1000))

const promise2 = Promise.reject(200)

Promsie.all([promise1, promise2]).then(() => {
  console.log('已完成')
}).catch(() => {
  console.log('已拒绝')
})

// 已拒绝

// Promise.all的数组同时执行

/* 
  Promise.all的规范决定了只有当所有的promise的实例状态都变成fulfilled，Promise.all才会变成fulfilled状态，才会执行.then 的resolve方法，否则只要有一个promise实例变成reject状态，Promise.all就会reject
*/

// 解决方法： 利用promise实例单一状态决定不会继承的原理，拦截promise的reject状态，使其then方法返回的新的Promise实例变成fulfilled状态，Promise.all就不会出现上述问题了


Promise.all([
  promise1.catch(() => ({ status: 'fail' })), 
  promise2.catch(() => ({ status: 'fail' })),
]).then(({ data1, data2}) => {
  console.log('已完成', data1, data2)
}).catch(() => {
  console.log('已拒绝')
})
```

6. 链式执行Promise的返回结果
   
```js
  // 方法1:
  const promise1 = new Promise(resolve => setTimeout(resolve, 1000))

  const promise2 = Promise.resolve(2)

  const promiseList = [() => promise1, () => promise2]

  async function main () {
    for (const createPromise of promiseList) {
      await createPromise()
    }
  }

  main()

  // 方法2

  promise1.then(() => promise2)
```

7. promise缺点
   
```js
  // 1. promise语法比较麻烦
  // 2. 书写不规范容易陷入回调地狱
```